### PR TITLE
Update statsbomb.py

### PR DESCRIPTION
**Pull request by gshirato**
Could not create `pg` because of `players.values()` taken as an argument.
I changed it to `pd.DataFrame({k:v for k, v in zip(players.keys(), players.values()})`, which might be ugly because I had to add `.T`.
Hope this helps :)

### CODE REVIEW

**Comment by TomDecroos** [comment]
Hi Gato,
Thanks for your commit and your interest in this package!
Could you explain a bit more what problem you are solving here?
Why is providing `players.values()` as an argument to pd.DataFrame() an issue?

**Comment by gshirato** [comment]
Turns out my `pd` version was `0.23.0`...

**Comment by gshirato** [comment]
I had to explain better. As my pandas version was `0.23.0`, `pd.DataFrame(players.values())` did not work. I updated pandas to `0.25.0` and it works! Thanks!

**Comment by TomDecroos** [comment]
Thanks for raising the issue anyway! I'll definitely keep the pandas requirement in mind for future troubles.

**Pull request closed without merging**
