### PR TITLE
Removal of dribbles where an unsuccessful action is followed by a foul

### PR DESCRIPTION
**Pull request by ksbharaj**
Created to get rid of more edge cases for incorrect dribbles. In particular, I noticed dribbles added at the end of actions (mainly passes) that were followed by a foul. Incorrect dribbles were added here between the end location of the action (e.g. pass) and the foul location.

EDIT: Change made to only remove dribbles for unsuccessful actions prior to a foul.

### CODE REVIEW

**Comment by ksbharaj** [comment]
Hi. Has anyone had the chance to review this? I have spotted a few more edge-cases that I was hoping to raise a PR for

**Comment by probberechts** [comment]
Could you provide a concrete example of a scenario that you try to fix?

**Comment by ksbharaj** [comment]
Sure. The example below is from 26-04-23, in the EPL match between Man City and Arsenal. 
Saka attempts a corner, which is unsuccessful due to a Foul from Ben White on Ederson (Image of opta events shown below).

image

Spadl however stitches a dribble from the end location of the unsuccessful pass and the foul location. 

image

The PR I raised addresses this. CSV outputs of the Opta events are also attached.

[Opta_events_Arsenal_Man_City.csv](https://github.com/ML-KULeuven/socceraction/files/12910430/Opta_events_Arsenal_Man_City.csv)
[Spadl_events_Arsenal_Man_City.csv](https://github.com/ML-KULeuven/socceraction/files/12910431/Spadl_events_Arsenal_Man_City.csv)

**Comment by ksbharaj** [comment]
Another one from Spurs vs Leicester on 17/09/22. Perisic's corner is unsuccessful because of a foul by Davinson Sanchez. Opta events shown below:

image

And then the Spadl events:

image

**Comment by probberechts** [comment]
Both of these are examples of corner kicks where a foul is called before the ball arrives. For consistency with StatsBomb (see 45a8d5f9c109463a012308bfdc3422e9f0dc353b) data, I think the correct thing to do here is to discard the corner kick.

**Comment by ksbharaj** [comment]
Hi @probberechts. I've made the changes now and discarded the event leading up to the foul (e.g. the corner or freekick as shown in the examples I shared)

**Pull request closed without merging**
